name: Publish on GitHub & Modrinth
on: [ workflow_dispatch ]

env:                                              
  VERSION: 0.4.1
  RELEASE_NAME: Improved Maps 0.4.1 for Minecraft 1.21.5
  CHANGE_LOG: |
    - Fixed some client-side issues
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

jobs:
  build:
    uses: './.github/workflows/build.yml'
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: wRyAdXG3
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: alpha
          changelog: "${{env.CHANGE_LOG}}"

          loaders: fabric
          files: |
            !(*-@(dev|sources|javadoc)).jar
            *-@(dev|sources|javadocs).jar
